### ISSUE TITLE
update to more recent Wordle

### ISSUE THREAD

**Issue by pietroppeter** [pietroppeter/wordle-it#12]
there have been recent updates to Wordle ([fixed a bug](https://twitter.com/powerlanguish/status/1480527244938256385?s=20), added stats icon). Changes in general can be tracked by the commit hash. I should track in some way this commit hash, I should  update to more recent js and create some nim code that helps with this automatic updates (and it should also help managing and curating the word selection).

**Comment by caco3** [comment]
I suggest you to migrate to my version as it is completely free :)
=> https://github.com/caco3/wordle-de

**Comment by pietroppeter** [comment]
Will not update and use from code and should actually deprecate the use of this (use it at your own risk
