### ISSUE TITLE
Richiesta di togliere dal DB i verbi

### ISSUE THREAD

**Issue by cometarossa** [pietroppeter/wordle-it#20]
Ciao Pietro, sarebbe possibile togliere dal DB i verbi o almeno quelli coniugati?

**Comment by Marmilli77** [comment]
Mi accodo alla richiesta. Il gioco sarebbe divertente se il dizionario comprendesse solo sostantivi al singolare e verbi all’infinito

**Comment by pietroppeter** [comment]
Ciao c'è un'altra versione di wordle in italiano che usa solo sostantivi al singolare e verbi all'infinito e suggerirei di usare quella: https://parolette.netlify.app 

Ormai questa versione ha iniziato con queste regole ed a questo punto non conto di cambiare.

**Comment by Marmilli77** [comment]
Grazie per il consiglio. Suggerisco comunque di valutare bene il cambio perché così non rispetta la filosofia del gioco originale ed è un vero peccato

**Comment by botolo** [comment]
In effetti mi incarto sempre anche io con i verbi coniugati

**Comment by valerionew** [comment]
> così non rispetta la filosofia del gioco originale

In quello inglese ci sono verbi coniugati e plurali

**Comment by Marmilli77** [comment]
> > così non rispetta la filosofia del gioco originale
> 
> In quello inglese ci sono verbi coniugati e plurali

Vero ma in italiano le coniugazioni sono un’enormità, tra l’altro sempre diverse non solo per ogni tempo ma anche per ogni persona singolare e plurale.

**Comment by pietroppeter** [comment]
ho "curato" il dizionario e rimosso molti verbi coniugati ma non alcuni rimangono lo stesso.
