### ISSUE TITLE
Wordle Kurdish

### ISSUE THREAD

**Issue by ovayolu** [pietroppeter/wordle-it#23]
Can I use your code to implement the Kurdish version of Wordle at www.kurdi.co.uk , please?

Many thanks

**Comment by pietroppeter** [comment]
Hi code is not really mine is taken as is from original author and adapted for the translation. Others have done the same starting either from original code or my translation, but you would be responsible for that. Another option is to use one of the many clones existing

**Comment by ovayolu** [comment]
I tried to adapt it by replacing Italian words/sentences with Kurdish but still it executes your version. Could you write which files should I modify? Many thanks...

**Comment by pietroppeter** [comment]
You have to change index.html and wordle-it.js
