### ISSUE TITLE
[Documentation request] Word of the day

### ISSUE THREAD

**Issue by PgnDvd** [pietroppeter/wordle-it#41]
How is the word of the day determined? Ideally I would like to pass it in the url (base64 encoded) for friends to guess a custom word

**Comment by PgnDvd** [comment]
Seems like this already exists actually: https://mywordle.org/wordle-italian/?w=irreb but I would still be curios to know how the word of the day is generated

**Comment by pietroppeter** [comment]
Word of the day is sequentially picked from a pre generated randomly shuffled list of words. Here details (part in Italian and part in English) that explain the specifics of the word list generation process: https://pietroppeter.github.io/wordle-it/dict/

**Comment by PgnDvd** [comment]
Awesome, thanks!
