### ISSUE TITLE
Stesso ip, stessa parola del giorno

### ISSUE THREAD

**Issue by fante76** [pietroppeter/wordle-it#44]
Ho provato ad aprire l'URL da dispositivi diversi agganciati alla medesima rete domestica, quindi uscenti tutti con lo stesso IP. Pur presentando la pagina iniziale con la griglia vuota, la parola del giorno rimane la stessa, quindi se da un dispositivo l'ho trovata negli altri posso trovarla sempre al primo colpo.
Forse potrebbe essere una soluzione agganciare la generazione di una nuova parola o la sessione giornaliera anche ad un cookie da depositare nel browser oppure usare lo user agent.

**Comment by pietroppeter** [comment]
la parola è la stessa per tutti e ce n'è una sola al giorno, il comportamento che riporta è quello atteso.
