### ISSUE TITLE
Avolo

### ISSUE THREAD

**Issue by fante76** [pietroppeter/wordle-it#55]
Soluzione di oggi
AVOLO
Non trovo una definizione di tale parola. Non è la prima volta che mi succede.
![Screenshot_2022-07-31-13-36-19-02_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/12963376/182024488-1c749a68-726b-4e8f-8496-50a09ec6c7ff.jpg)

**Comment by pietroppeter** [comment]
Nonno, avo. Parola obsoleta e letteraria, usato soprattutto nei composti bisavolo e trisavolo.

- https://dizionario.internazionale.it/parola/avolo
- https://www.grandidizionari.it/Dizionario_Italiano/parola/A/avolo.aspx
- https://dizionaripiu.zanichelli.it/cultura-e-attualita/le-parole-del-giorno/parola-del-giorno/la_parola_del_giorno__avo__avolo__bisavo__bisavolo/
