### ISSUE TITLE
No new word today

### ISSUE THREAD

**Issue by SemperYak** [pietroppeter/wordle-it#62]
Hello and thank you for this app!

FYI, there is no new word today - it still shows the answer/word from yesterday. 

I tried different browsers, private mode, clear cache, etc to be sure it wasn’t an issue on my end. 

Thank you!

**Comment by pietroppeter** [comment]
hi and welcome. If in your country the there was change to [Daylight saving time](https://en.wikipedia.org/wiki/Daylight_saving_time) this is unfortunately a known issue. It will resume to normal tomorrow. for the new word of today you should be able to use: https://par-le.github.io/gioco/

**Comment by SemperYak** [comment]
Ah, perfect! Thanks for the clarification :)
