### ISSUE TITLE
Vizzi

### ISSUE THREAD

**Issue by paololago** [pietroppeter/wordle-it#77]
Buongiorno 
L'applicazione ha accettato la parola "vizzi" che dovrebbe essere sbagliata e inesistente. Cordiali saluti

**Comment by pietroppeter** [comment]
Salve, in effetti sentita senza contesto la parola può sembrare inesistente ma si tratta della forma plurale dell'aggettivo "vizzo": https://it.m.wiktionary.org/wiki/vizzo

La ringrazio del messaggio e le auguro una buona giornata,
Pietro

**Comment by paololago** [comment]
ops.. grazie mille e scusi il disturbo!
