### ISSUE TITLE
Due parole diverse da due browser differenti

### ISSUE THREAD

**Issue by linfamonte** [pietroppeter/wordle-it#78]
Se apro il gioco da un browser e lo rifaccio da un altro, a volte cambia la parola, come mai?

**Comment by linfamonte** [comment]
ad esempio oggi, ho visto il gioco per due parole, la prima tutto ok (magma), non sono sicura se la seconda sia un'anticipazione sulla prossima, (presa)

**Comment by pietroppeter** [comment]
strano, mi immagino possa succedere solo se il browser vede un altro giorno

**Comment by linfamonte** [comment]
Sai per caso se la parola di domani è "oltre"? Me lo ha fatto di nuovo

**Comment by linfamonte** [comment]
(non so come il browser veda un altro giorno, forse registra da qualche parte che l'ho già fatto e mi presenta quello successivo? Chissà)

**Comment by pietroppeter** [comment]
ah, può essere che su i due browser stia usando le due diverse implementazioni, che durante il periodo estivo (tra i cambi d'ora) sono disallineate di un giorno:
- https://pietroppeter.github.io/wordle-it/
- https://par-le.github.io/gioco/

(però per favore si astenga di menzionare le soluzioni del gioco che è spoiler ;))

**Comment by linfamonte** [comment]
Chiedo scusa per lo spoiler, (!)

Esistono varianti che ti permettono di divertirti anche sapendo la parola, ad esempio usarla per creare una frase di senso compiuto, ecc.

**Comment by linfamonte** [comment]
usandola*

**Comment by linfamonte** [comment]
Argomento chiuso, per me
