### ISSUE TITLE
Non riesco a condividere su whatsapp

### ISSUE THREAD

**Issue by umpire274** [pietroppeter/wordle-it#81]
Mi ritorna un messaggio "non puoi inviare un messaggio vuoto"

**Comment by umpire274** [comment]
Aggiungo che il mio whatsapp ha due account nella stessa applicazione ( Android 14.1; WhatsApp 2.24.20.89)

**Comment by umpire274** [comment]
Ho eliminato un account dal mio smartphone ma continua a visualizzare il messaggio "non puoi inviare un messaggio vuoto". Ho provato anche a utilizzare l'opzione di condivisione 'copia messaggio' ma il messaggio effettivamente è vuoto.
E' come se quando premo il tasto 'CONDIVIDI' alla riga 1427 del sorgente 'wordle-it.js' non venga valorizzata la variabile 'l' col testo del messaggio.

**Comment by pietroppeter** [comment]
Ciao credo sia questo problema https://github.com/pietroppeter/wordle-it/issues/37#issuecomment-1049609156

**Comment by pietroppeter** [comment]
Questa versione comunque non ha maintenance il codice rimarrà così (la versione alternativa linkato nel commento ha lo sfasamento di un giorno durante ora legale)

**Comment by umpire274** [comment]
Grazie. Purtroppo passando da questa versione a quella nuova che mi suggerisci, perdo tutte le statistiche fatte finora, vero?

**Comment by pietroppeter** [comment]
(Conversazione un po' qui e un po' su mastodon https://mastodon.uno/@pietroppeter/113344935554791546)

**Comment by umpire274** [comment]
Grazie mille ancora. Userò Chrome per non perdere le statistiche.
