### ISSUE TITLE
RETE SICURA VODAFONE

### ISSUE THREAD

**Issue by thebenellis1** [pietroppeter/wordle-it#83]
Rete Sicura Family ha bloccato questo contenuto.
Il contenuto all'indirizzo https://pietroppeter.github.io/ è stato valutato non sicuro o non
appropriato. Rete Sicura Family raccomanda di chiudere questa pagina e ritornare al sicuro.

**Comment by thebenellis1** [comment]
Continua a momenti e giorni alterni. Capita che il sito venga bloccato al mattino ma si possa giocare al pomeriggio...

**Comment by pietroppeter** [comment]
eh, mi spiace ma non credo possa farci nulla al riguardo. buona giornata
